### ISSUE TITLE
sudo ndm config --create error

### ISSUE THREAD

**Issue by naufalyafisusanto** [gitbls/ndm#11]
hi, i found a problem when running the command "sudo ndm config --create"

pipernigrum@pipernigrum:/ $ sudo ndm config --create
Traceback (most recent call last):
  File "/usr/local/bin/ndm", line 1028, in <module>
    pd.dbread(ckcfg=pd.args.ckcfg)
  File "/usr/local/bin/ndm", line 306, in dbread
    self.db['cfg']['subnet'] = '.'.join([ips[0], ips[1], ips[2]])
                                                 ~~~^^^
IndexError: list index out of range

I use bind9 and isc-dhcp-server

**Comment by gitbls** [comment]
Sorry you're having an issue. I need some additional information:
* What OS and version?
* Please provide the output from:
  * `uname -a`
  * `cat /etc/os-release`
  * `python --version`

**Comment by naufalyafisusanto** [comment]
Sorry, I have resolved the problem above by restarting, but I found a new problem when build the config

Traceback (most recent call last):
  File "/usr/local/bin/ndm", line 1034, in <module>
    pd.args.func(pd)
  File "/usr/local/bin/ndm", line 479, in cmd_build
    pd.dns.endbuild()
  File "/usr/local/bin/ndmdnsbind.py", line 163, in endbuild
    slow = rze[0].split('.')[3]
           ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

uname -a:
Linux pipernigrum 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

cat /etc/os-release:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

python --version:
Python 3.11.2

**Comment by naufalyafisusanto** [comment]
Thank you, the error above has been resolved, apparently after I checked the configuration, I didn't include dhcpsubnet. but I'm still confused about one thing. I have set a static IP address for a device with a MAC address, I have built and installed it, I have also restarted bind and isc-dhcp but my IP address remains unchanged (it still remains from the DHCP server)

**Comment by gitbls** [comment]
You didn't say that you restarted the device that you set the configuration for. It doesn't pick up the new address magically, you either need to restart the device or cause it to renew its DHCP lease. Please confirm what steps you took on the device to renew its DHCP lease.

**Comment by gitbls** [comment]
Closing this issue due to lack of activity. OP, please feel free to re-open this issue, or a new one, with further details.
